
print("Hello there! Welcome to the world of Pokémon! My name is Oak! People call me the Pokémon Prof! This world is inhabited by creatures called Pokémon! For some people, Pokémon are pets. Other use them for fights. Myself… I study Pokémon as a profession. First, what is your name?")
print(" ")
print("Name?")
player = input()
print(" ")
print("Right! So your name is" , player , "! This is my grandson. He's been your rival since you were a baby. …Erm, what is his name again?")
print(" ")
print("Rival Name?")
rival = input()
print("That's right! I remember now! His name is" , rival , "!" , player , "! Your very own Pokémon legend is about to unfold! A world of dreams and adventures with Pokémon awaits! Let's go!")
print(" ")
print("Press Continue")
cont = input()
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("*You wake up in your bed*")
print("go downstairs? Y/N?")
choose = input()

if choose == 'N' or choose == 'No' or choose == 'no' or choose == 'n':
    print("*You lay in bed for a while*")

if choose == 'Y' or choose == 'Yes' or choose == 'yes' or choose == 'y':
    print("*you make your way to the livingroom*")
    print(" ")
    print("Go outside? Y/N?")

    choose = input()
    if choose == 'N' or choose == 'No' or choose == 'no' or choose == 'n':
        print("*you stand there*")

    if choose == 'Y' or choose == 'Yes' or choose == 'yes' or choose == 'y':
        print("*you make your way outside*")
        print("approach tall grass? (Y/N)")

        choose = input()

        if choose == 'N' or choose == 'No' or choose == 'no' or choose == 'n':
            print("*you stand there*")

        if choose == 'Y' or choose == 'Yes' or choose == 'yes' or choose == 'y':
            print("Hey! Wait! Don't go out! It's unsafe! Wild Pokémon live in tall grass! You need your own Pokémon for your protection. I know! Here, come with me!")
            print("*he grabs your arm and leads you to his lab, not far from your home*")
            print(" ")
            print("press Continue")
            cont = input()
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print("*as you arrive in the lab you see a young man standing impatiently, he looks over at you and the man*")
            print(" ")
            print("Gramps! I'm fed up with waiting!")
            print(" ")
            print(rival, "? Let me think… Oh, that's right, I told you to come! Just wait! Here,", player , "! There are three Pokémon here. Haha! The Pokémon are held inside these Poké Balls. When I was young, I was a serious Pokémon Trainer. But now, in my old age, I have only these three left. You can have one. Go on, choose!")
            print(" ")
            print("Hey! Gramps! What about me?")
            print(" ")
            print("Be patient!" , rival , ". You can have one, too!")
            print(" ")
            print("Now," , player , ". Inside those three Poké Balls are Pokémon. Which one will you choose for yourself?")
            print(" ")
            print(" ")
            print("press continue")
            cont = input()
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print("*you see three pokeballs on the table. charmander, squirtle, and bulbasaur*")
            print("which will you choose? (C/S/B)?")
            choose = input()
            if choose == 'C' or choose == 'CHARMANDER' or choose == 'c' or choose == 'charmander' or choose == 'Charmander':
                print("You got CHARMANDER")
            if choose == 'S' or choose == 'SQUIRTLE' or choose == 'Squirtle' or choose == 's' or choose == 'squirtle':
                print("you got SQUIRTLE")
            if choose == 'B' or choose == 'BULBASAUR' or choose == 'b' or choose == 'bulbasaur' or choose == 'Bulbasaur':
                print("you got BULBASAUR")

            print("press continue")
            cont = input()
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
