print("===============Welcome to SPACE DUNGEON===================")
print("Before we begin, let's go over your files.")
print("What is your name?")
print(" ")
Name = input()
print(" ")
print("So. you are" , Name , "?")
print(" ")
print("What class are you?")
print(" ")
Class = input()
print("Interesting....you chose" , Class , "....very well. That matches the reccords")
print(" ")
print("How much health and magic do you have?")
print("(It must add up to 100 between the two stats.)")
print(" ")
print("Health?")
Health = input()
print(" ")
print("Magic?")
Magic = input()
print(" ")
print("I see... let me be sure I have this right before we begin.")
print(" ")
print("So. You are" , Name , "the" , Class , "You have" , Health , "Health, and" , Magic , "Magic.")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Press any button to continue..")
Any = input()
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print("......")
print(" ")
print("You have run out of oxygen")
print(" ")
print("......................YOU HAVE DIED........................")
print("Press any button to continue..")
Any = input()
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("///////////THANK YOU for playing the Space Dungeon demo////////////")
